directory : @musicDirectory@
import:
    move: no
    write: yes
    copy: yes
    resume: no

pluginpath : @configHome@/beets/plugins
library : @dataHome@/beets/library.db
plugins : chroma fromfilename fetchart

paths:
    default: Artists/$albumartist/$album%aunique{}/CD$disc/$track $title
    singleton: Artists/$artist/singles/$title
    comp: Compilations/$album%aunique{}/$track $title
    albumtype:soundtrack: Soundtracks/$album/$track $title

asciify_paths: yes

ui:
    color: yes

languages: [en, es, fr, de, it]
detail: yes
